CREATE TABLE [dbo].[Dim_Calendar] (

	[DateKey] int NOT NULL, 
	[Date] date NOT NULL, 
	[Day] int NOT NULL, 
	[DaySuffix] char(2) NOT NULL, 
	[DayName] varchar(10) NOT NULL, 
	[DayOfWeek] int NOT NULL, 
	[DayOfWeekInMonth] int NOT NULL, 
	[DayOfYear] int NOT NULL, 
	[IsWeekend] bit NOT NULL, 
	[WorkingDayOfMonth] int NULL, 
	[Week] int NOT NULL, 
	[FirstOfWeek] date NOT NULL, 
	[LastOfWeek] date NOT NULL, 
	[WeekOfMonth] int NOT NULL, 
	[Month] int NOT NULL, 
	[MonthName] varchar(10) NOT NULL, 
	[MonthNameShort] char(3) NOT NULL, 
	[FirstOfMonth] date NOT NULL, 
	[LastOfMonth] date NOT NULL, 
	[FirstOfNextMonth] date NOT NULL, 
	[LastOfNextMonth] date NOT NULL, 
	[Quarter] int NOT NULL, 
	[FirstOfQuarter] date NOT NULL, 
	[LastOfQuarter] date NOT NULL, 
	[Year] int NOT NULL, 
	[FirstOfYear] date NOT NULL, 
	[LastOfYear] date NOT NULL, 
	[FirstOfFinancialYear] date NOT NULL, 
	[LastOfFinancialYear] date NOT NULL, 
	[FinancialPeriod] int NOT NULL, 
	[FinancialQuarter] int NOT NULL, 
	[FinancialYear] char(9) NOT NULL, 
	[InTheFinancialYTD] bit NOT NULL, 
	[FinancialYearFilter] varchar(9) NULL, 
	[MonthsAgo] int NOT NULL, 
	[FinancialYearsAgo] int NOT NULL, 
	[IsLeapYear] bit NOT NULL, 
	[Has53Weeks] bit NOT NULL, 
	[Has53ISOWeeks] bit NOT NULL, 
	[MMYYYY] char(6) NOT NULL, 
	[Style101] char(10) NOT NULL, 
	[Style103] char(10) NOT NULL, 
	[Style112] char(8) NOT NULL, 
	[Style120] char(10) NOT NULL
);

